=== TheFlightSims/windowsserver-mgmttools/vlmcsd-beta/license-manager/KmsDataBase.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="KmsData" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msprop="urn:schemas-microsoft-com:xml-msprop">

  <xs:simpleType name="Guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})|(\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}\})"/>
      <xs:minLength value="36"/>
      <xs:maxLength value="38"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ProductKey">
    <xs:restriction base="xs:string">
      <xs:pattern value="(?!^.*N.*N.*$)([BCDFGHJKMPQRTVWXY2-9N]{5}\-){4}[BCDFGHJKMPQRTVWXY2-9N]{4}[BCDFGHJKMPQRTVWXY2-9]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="KmsProtocol">
    <xs:restriction base="xs:string">
      <xs:enumeration value="4.0"/>
      <xs:enumeration value="5.0"/>
      <xs:enumeration value="6.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="KmsDataVersion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="2.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="EPid">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{5}-[0-9]{5}-[0-9]{3}-[0-9]{6}-03-[0-9]{4,5}-[0-9]{4,5}\.0000-(36[0-6]|3[0-5][0-9]|[0-2][0-9]{2})20[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="IdName">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z][A-Za-z0-9_]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PositiveInteger">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="2147483647"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VlmcsdKmsIds">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="VlmcsdEpidIds">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EPID_UNKNOWN"/>
      <xs:enumeration value="EPID_WINDOWS"/>
      <xs:enumeration value="EPID_OFFICE2010"/>
      <xs:enumeration value="EPID_OFFICE2013"/>
      <xs:enumeration value="EPID_OFFICE2016"/>
      <xs:enumeration value="EPID_OFFICE2019"/>
      <xs:enumeration value="EPID_WINDOWS_CHINA_GOV"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="GroupId">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="-1"/>
      <xs:maxInclusive value="99999"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="KeyId">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="-1"/>
      <xs:maxInclusive value="999999999"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VlmcsdIndex">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="-1"/>
      <xs:maxInclusive value="127"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VlmcsdIndex2">
    <xs:restriction base="VlmcsdIndex">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VlmcsdAppIds">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="BuildNumber">
    <xs:restriction base="xs:unsignedShort"/>
  </xs:simpleType>

  <xs:simpleType name="PlatformId">
    <xs:restriction base="xs:unsignedInt">
      <xs:maxExclusive value="100000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="KmsData">
    <xs:complexType>
      <xs:choice minOccurs="3" maxOccurs="3">
        <xs:element name="WinBuilds" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="WinBuild" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="BuildNumber" type="BuildNumber" use="required"/>
                  <xs:attribute name="DisplayName" type="xs:string" use="required"/>
                  <xs:attribute name="PlatformId" type="PlatformId" use="required"/>
                  <xs:attribute name="MayBeServer" type="xs:boolean" use="optional" default="false"/>
                  <xs:attribute name="UseForEpid" type="xs:boolean" use="optional" default="false"/>
                  <xs:attribute name="UsesNDR64" type="xs:boolean" use="optional" default="false"/>
                  <xs:attribute name="ReleaseDate" type="xs:dateTime" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="CsvlkItems" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CsvlkItem" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Activate" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="KmsItem" type="Guid" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="IniFileName" type="IdName" use="optional"/>
                  <xs:attribute name="DisplayName" type="xs:string" use="required"/>
                  <xs:attribute name="Id" type="Guid" use="required"/>
                  <xs:attribute name="ReleaseDate" type="xs:dateTime" use="required"/>
                  <xs:attribute name="IsLab" type="xs:boolean" use="optional" default="false"/>
                  <xs:attribute name="IsPreview" type="xs:boolean" use="optional" default="false"/>
                  <xs:attribute name="VlmcsdIndex" type="VlmcsdIndex" use="optional" default="-1"/>
                  <xs:attribute name="GroupId" type="GroupId" use="optional" default="-1"/>
                  <xs:attribute name="MinKeyId" type="KeyId" use="optional" default="-1"/>
                  <xs:attribute name="MaxKeyId" type="KeyId" use="optional" default="-1"/>
                  <xs:attribute name="EPid" type="EPid" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="AppItems" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="AppItem" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation xml:lang="en">
                    Defines a KMS Application. There are only three Applications: Windows, Office 2010 and Office 2013+. On a genuine KMS server each Application has a separate counter for currently active clients. Thus each Application needs to be charged seperately.
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="KmsItem" minOccurs="0" maxOccurs="unbounded">
                      <xs:annotation>
                        <xs:documentation xml:lang="en">
                          A KMS Item is a group of KMS client products (e.g. all Windows 10 Volume License editions). A genuine server uses it to either grant or deny activation. It either activates all or none SKUs in a "KMS Counted Item".
                        </xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="SkuItem" minOccurs="0" maxOccurs="unbounded">
                            <xs:annotation>
                              <xs:documentation xml:lang="en">
                                An SKU Item is a specific KMS client product (e.g. Windows 10 Enterprise 2016 LTSB N).
                              </xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:attribute name="Id" use="required" type="Guid">
                                <xs:annotation>
                                  <xs:documentation xml:lang="en">
                                    The GUID of an SKU aka SKU ID or Activation ID. This attribute is required. (slmgr.vbs calls it Activation Id, most other MS software including ospp.vbs calls it SKU ID).
                                  </xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="DisplayName"  type="xs:string" use="required">
                                <xs:annotation>
                                  <xs:documentation xml:lang="en">
                                    A more descriptive name of the SKU item. This attribute is required. It is used in user interfaces and logging.
                                  </xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="Gvlk" type="ProductKey">
                                <xs:annotation>
                                  <xs:documentation xml:lang="en">
                                    Optional, but recommended: If you enter a GVLK in a Microsoft product, it will activate using a configurable KMS server. There are millions of valid GVLKs but MS publishes usually just one. This one should be entered here.
                                  </xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="IsGeneratedGvlk"  type="xs:boolean" default="false">
                                <xs:annotation>
                                  <xs:documentation xml:lang="en">
                                    Optional, default false: Set this to true if you only have a GVLK that is generated by a tool. These GVLKs have incorrect hashes and the computer does not get a "Windows Genuine Ticket".
                                  </xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Id" use="required" type="Guid">
                          <xs:annotation>
                            <xs:documentation xml:lang="en">
                              The GUID of a KMS item aka KMS Counted ID. This attribute is required.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="DisplayName"  type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation xml:lang="en">
                              A more descriptive name of the KMS item. This attribute is required. It is used in user interfaces and logging.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="IsPreview"  type="xs:boolean" default="false">
                          <xs:annotation>
                            <xs:documentation xml:lang="en">
                              Optional, default false: Should be set to true, if the KMS Item is a group of beta or preview products. Used in KMS emulator detection because genuine KMS servers do not activate beta or preview products.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="IsRetail" type="xs:boolean" default="false">
                          <xs:annotation>
                            <xs:documentation xml:lang="en">
                              Optional, default false: Should be set to true, if the KMS Item is a group of retail (non-VL) products.  Used in KMS emulator detection because genuine KMS servers do not activate beta or preview products.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="DefaultKmsProtocol" default="6.0" type="KmsProtocol">
                          <xs:annotation>
                            <xs:documentation xml:lang="en">
                              Optional, default 6.0: Set this to the KMS protocol, that this KMS Item normally uses. Note that Office product groups normally use the KMS protocol of the operating system. Exceptions are Office 2010 (always uses 4.0) and Office 2013 under Windows 7 (uses 5.0 in this case)
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="NCountPolicy" type="PositiveInteger" default="25">
                          <xs:annotation>
                            <xs:documentation xml:lang="en">
                              Optional, default 25: Set this to the number of minimum clients a KMS server must report for an activation to succeed (25 for Windows clients, 5 for Windows Servers and Office)
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="CanMapToDefaultCsvlk" type="xs:boolean" use="optional" default="true"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" use="required" type="Guid">
                    <xs:annotation>
                      <xs:documentation xml:lang="en">
                        The GUID of an Application aka Application ID. This attribute is required.
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="DisplayName" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation xml:lang="en">
                        A more descriptive name of the Application. This attribute is required. It is used in user interfaces and logging.
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="VlmcsdIndex" type="VlmcsdIndex2" use="required"/>
                  <xs:attribute name="MinActiveClients" type="PositiveInteger" use="optional" default="50"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
      <xs:attribute name="Version" use="required" type="KmsDataVersion">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Required: Used to correct minor behavior differences in License Manager. Must currently be set to "1.0". Note: This is not the schema version
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="Author" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Required: Put your name in this field if you create your own version of a License Manager database
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:key id="SkuId" name="SkuItem_Constraint">
      <xs:selector xpath=".//SkuItem" />
      <xs:field xpath="@Id" />
    </xs:key>
    <xs:unique id="Gvlk" name="Gvlk_Constraint">
      <xs:selector xpath=".//SkuItem" />
      <xs:field xpath="@Gvlk" />
    </xs:unique>
    <xs:key id="KmsId" name="KmsItem_Constraint">
      <xs:selector xpath=".//KmsItem" />
      <xs:field xpath="@Id" />
    </xs:key>
    <xs:unique id="VlmcsdEpidNameAppId" name="VlmcsdEpidNameAppItem_Constraint">
      <xs:selector xpath=".//AppItem" />
      <xs:field xpath="@VlmcsdEpidName" />
    </xs:unique>
    <xs:key id="AppId" name="AppItem_Constraint">
      <xs:selector xpath=".//AppItem" />
      <xs:field xpath="@Id" />
    </xs:key>
  </xs:element>
</xs:schema>

=== TheFlightSims/windowsserver-mgmttools/vlmcsd-beta/license-manager/LmInternalDatabase.xml
<?xml version="1.0" encoding="Windows-1252"?>
<KmsData
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2.0" Author="Hotbird64" xsi:noNamespaceSchemaLocation="KmsDataBase.xsd">
	<WinBuilds>
		<WinBuild BuildNumber="103" ReleaseDate="1992-04-06T00:00:00Z" DisplayName="Windows 3.1" PlatformId="55041" />
		<WinBuild BuildNumber="300" ReleaseDate="1993-11-08T00:00:00Z" DisplayName="Windows for Workgroup 3.11" PlatformId="55041" />
		<WinBuild BuildNumber="528" ReleaseDate="1992-04-06T00:00:00Z" DisplayName="Windows NT 3.1" PlatformId="55041" />
		<WinBuild BuildNumber="807" ReleaseDate="1994-09-21T00:00:00Z" DisplayName="Windows NT 3.5" PlatformId="55041" />
		<WinBuild BuildNumber="950" ReleaseDate="1995-08-24T00:00:00Z" DisplayName="Windows 95" PlatformId="55041" />
		<WinBuild BuildNumber="999" ReleaseDate="1996-07-29T00:00:00Z" DisplayName="Windows 96" PlatformId="55041" />
		<WinBuild BuildNumber="1057" ReleaseDate="1995-05-30T00:00:00Z" DisplayName="Windows NT 3.51" PlatformId="55041" />
		<WinBuild BuildNumber="1175" ReleaseDate="1996-07-29T00:00:00Z" DisplayName="Windows NT 4.0" PlatformId="55041" />
		<WinBuild BuildNumber="1381" ReleaseDate="1996-07-29T00:00:00Z" DisplayName="Windows NT 4.0" PlatformId="55041" />
		<WinBuild BuildNumber="1998" ReleaseDate="1995-08-24T00:00:00Z" DisplayName="Windows 98 (First Build)" PlatformId="55041" />
		<WinBuild BuildNumber="2195" ReleaseDate="2000-02-17T00:00:00Z" DisplayName="Windows 2000" PlatformId="55041" />
		<WinBuild BuildNumber="2600" ReleaseDate="2001-10-25T00:00:00Z" DisplayName="Windows XP Build 2600" PlatformId="55041" />
		<WinBuild BuildNumber="2700" ReleaseDate="2004-10-12T00:00:00Z" DisplayName="Windows XP build 2700" PlatformId="55041" />
		<WinBuild BuildNumber="3000" ReleaseDate="2000-09-14T00:00:00Z" DisplayName="Windows ME" PlatformId="55041" />
		<WinBuild BuildNumber="3790" ReleaseDate="2003-03-28T00:00:00Z" DisplayName="Windows Server 2003 / XP 64-bit" PlatformId="55041" MayBeServer="true" />
		<WinBuild BuildNumber="5111" ReleaseDate="2001-10-25T00:00:00Z" DisplayName="Windows XP - Beta" PlatformId="55041" />
		<WinBuild BuildNumber="6000" ReleaseDate="2006-11-30T00:00:00Z" DisplayName="Windows Vista / Server 2008 without SP" PlatformId="55041" MayBeServer="true" />
		<WinBuild BuildNumber="6001" ReleaseDate="2008-02-04T00:00:00Z" DisplayName="Windows Vista / Server 2008 SP1" PlatformId="55041" MayBeServer="true" />
		<WinBuild BuildNumber="6002" ReleaseDate="2009-05-26T00:00:00Z" DisplayName="Windows Vista / Server 2008 SP2" PlatformId="55041" MayBeServer="true" />
		<WinBuild BuildNumber="7224" ReleaseDate="2003-03-28T00:00:00Z" DisplayName="Windows Essential Business Server 2008 R2" PlatformId="55041" MayBeServer="true" />
		<WinBuild BuildNumber="7600" ReleaseDate="2009-10-22T00:00:00Z" DisplayName="Windows 7 / Server 2008 R2 without SP" PlatformId="55041" MayBeServer="true" />
		<WinBuild BuildNumber="7601" ReleaseDate="2011-02-22T00:00:00Z" DisplayName="Windows 7 / Server 2008 R2 SP1" PlatformId="55041" MayBeServer="true" />
		<WinBuild BuildNumber="9200" ReleaseDate="2012-10-26T00:00:00Z" DisplayName="Windows 8 / Server 2012" PlatformId="5426" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="9600" ReleaseDate="2013-10-18T00:00:00Z" DisplayName="Windows 8.1 / Server 2012 R2" PlatformId="6401" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="10240" ReleaseDate="2015-07-29T00:00:00Z" DisplayName="Windows 10 1507" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="10586" ReleaseDate="2015-11-10T00:00:00Z" DisplayName="Windows 10 1511" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="14393" ReleaseDate="2016-08-02T00:00:00Z" DisplayName="Windows 10 1607 / Server 2016" PlatformId="3612" MayBeServer="true" UseForEpid="true" UsesNDR64="true" />
		<WinBuild BuildNumber="15063" ReleaseDate="2017-04-05T00:00:00Z" DisplayName="Windows 10 1703" PlatformId="3612" UsesNDR64="true" />
		<WinBuild BuildNumber="16299" ReleaseDate="2017-10-17T00:00:00Z" DisplayName="Windows 10 1709" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="17134" ReleaseDate="2018-04-30T00:00:00Z" DisplayName="Windows 10 1803" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="17763" ReleaseDate="2018-10-02T00:00:00Z" DisplayName="Windows 10 1809 / Server 2019" PlatformId="3612" MayBeServer="true" UseForEpid="true" UsesNDR64="true" />
		<WinBuild BuildNumber="18362" ReleaseDate="2019-03-20T00:00:00Z" DisplayName="Windows 10 1903" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="18363" ReleaseDate="2019-11-12T00:00:00Z" DisplayName="Windows 10 1909" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="19041" ReleaseDate="2020-03-22T00:00:00Z" DisplayName="Windows 10 2004" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="19042" ReleaseDate="2020-09-22T00:00:00Z" DisplayName="Windows 10 20H2" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="19043" ReleaseDate="2021-04-08T00:00:00Z" DisplayName="Windows 10 21H1" PlatformId="3612" UsesNDR64="true" />
		<WinBuild BuildNumber="19044" ReleaseDate="2021-11-16T00:00:00Z" DisplayName="Windows 10 21H2" PlatformId="3612" UsesNDR64="true" />
		<WinBuild BuildNumber="20348" ReleaseDate="2021-08-18T00:00:00Z" DisplayName="Windows Server 2022" PlatformId="3612" MayBeServer="true" UseForEpid="true" UsesNDR64="true" />
		<WinBuild BuildNumber="20279" ReleaseDate="2020-09-22T00:00:00Z" DisplayName="Windows 10X" PlatformId="3612" MayBeServer="true" />
		<WinBuild BuildNumber="22000" ReleaseDate="2021-06-24T00:00:00Z" DisplayName="Windows 11 21H2" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="22610" ReleaseDate="2022-09-21T00:00:00Z" DisplayName="Windows 11 22H2" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="22621" ReleaseDate="2022-09-21T00:00:00Z" DisplayName="Windows 11 22H2" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="22631" ReleaseDate="2023-09-21T00:00:00Z" DisplayName="Windows 11 23H2" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="25247" ReleaseDate="2022-12-01T00:00:00Z" DisplayName="Windows 11 22H2 Preview" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="25252" ReleaseDate="2022-12-01T19:08:21Z" DisplayName="Windows Server 2022 (22H2) vNext" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="25246" ReleaseDate="2022-12-01T19:08:21Z" DisplayName="Windows Server 2022 (22H2) vNext" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
		<WinBuild BuildNumber="26040" ReleaseDate="2024-01-26T11:10:00Z" DisplayName="Windows Server 2025 (23H2) vNext" PlatformId="3612" MayBeServer="true" UsesNDR64="true" />
	</WinBuilds>
	<CsvlkItems>
		<CsvlkItem DisplayName="Windows Server 2022" VlmcsdIndex="0" GroupId="4573" MinKeyId="30000" MaxKeyId="20029999" IniFileName="Windows" ReleaseDate="2021-08-18T00:00:00Z" EPid="03612-04573-018-246887-03-1033-20348.0000-1862021" Id="661f7658-7035-4b4c-9f35-010682943ec2">
			<Activate KmsItem="b74263e4-0f92-46c6-bcf8-c11d5efe2959" />
			<Activate KmsItem="58e2134f-8e11-4d17-9cb2-91069c151148" />
			<Activate KmsItem="7fde5219-fbfa-484a-82c9-34d1ad53e856" />
			<Activate KmsItem="3c40b358-5948-45af-923b-53d21fcc7e79" />
			<Activate KmsItem="cb8fc780-2c05-495a-9710-85afffc904d7" />
			<Activate KmsItem="33e156e4-b76f-4a52-9f91-f641dd95ac48" />
			<Activate KmsItem="8fe53387-3087-4447-8985-f75132215ac9" />
			<Activate KmsItem="8a21fdf3-cbc5-44eb-83f3-fe284e6680a7" />
			<Activate KmsItem="0fc6ccaf-ff0e-4fae-9d08-4370785bf7ed" />
			<Activate KmsItem="ca87f5b6-cd46-40c0-b06d-8ecd57a4373f" />
			<Activate KmsItem="b2ca2689-a9a8-42d7-938d-cf8e9f201958" />
			<Activate KmsItem="8665cb71-468c-4aa3-a337-cb9bc9d5eaac" />
			<Activate KmsItem="8456efd3-0c04-4089-8740-5b7238535a65" />
			<Activate KmsItem="6e9fc069-257d-4bc4-b4a7-750514d32743" />
			<Activate KmsItem="212a64dc-43b1-4d3d-a30c-2fc69d2095c6" />
			<Activate KmsItem="969fe3c0-a3ec-491a-9f25-423605deb365" />
			<Activate KmsItem="11b15659-e603-4cf1-9c1f-f0ec01b81888" />
			<Activate KmsItem="8449b1fb-f0ea-497a-99ab-66ca96e9a0f5" />
		</CsvlkItem>
		<CsvlkItem DisplayName="Windows Server 2022 VL Additional Lab" IsLab="true" GroupId="4575" MinKeyId="0" MaxKeyId="49999" IniFileName="Windows" ReleaseDate="2021-08-18T00:00:00Z" Id="22105925-48c3-4ff4-a294-f654bb27e390">
			<Activate KmsItem="b74263e4-0f92-46c6-bcf8-c11d5efe2959" />
			<Activate KmsItem="e1c51358-fe3e-4203-a4a2-3b6b20c9734e" />
			<Activate KmsItem="58e2134f-8e11-4d17-9cb2-91069c151148" />
			<Activate KmsItem="7fde5219-fbfa-484a-82c9-34d1ad53e856" />
			<Activate KmsItem="bbb97b3b-8ca4-4a28-9717-89fabd42c4ac" />
			<Activate KmsItem="3c40b358-5948-45af-923b-53d21fcc7e79" />
			<Activate KmsItem="6d646890-3606-461a-86ab-598bb84ace82" />
			<Activate KmsItem="cb8fc780-2c05-495a-9710-85afffc904d7" />
			<Activate KmsItem="33e156e4-b76f-4a52-9f91-f641dd95ac48" />
			<Activate KmsItem="8fe53387-3087-4447-8985-f75132215ac9" />
			<Activate KmsItem="8a21fdf3-cbc5-44eb-83f3-fe284e6680a7" />
			<Activate KmsItem="0fc6ccaf-ff0e-4fae-9d08-4370785bf7ed" />
			<Activate KmsItem="ca87f5b6-cd46-40c0-b06d-8ecd57a4373f" />
			<Activate KmsItem="b2ca2689-a9a8-42d7-938d-cf8e9f201958" />
			<Activate KmsItem="8665cb71-468c-4aa3-a337-cb9bc9d5eaac" />
			<Activate KmsItem="8456efd3-0c04-4089-8740-5b7238535a65" />
			<Activate KmsItem="6e9fc069-257d-4bc4-b4a7-750514d32743" />
			<Activate KmsItem="969fe3c0-a3ec-491a-9f25-423605deb365" />
			<Activate KmsItem="212a64dc-43b1-4d3d-a30c-2fc69d2095c6" />
			<Activate KmsItem="8449b1fb-f0ea-497a-99ab-66ca96e9a0f5" />
